URL_SERVICE = "https://cd514f6b-f746-4067-bcdf-9a13bb09a829.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/var/www/backend/logs/error.log"
CREATE_NEW_ORDER = "/api/v1/orders"
GET_ORDER = "/api/v1/orders/track?t="
